services:
  postgres:
    image: postgres:latest
    container_name: postgres_logger2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESS_DB=${POSTGRESS_DB}
    ports:
      - "5432:5432"
    volumes:
      - logger2_data:/var/lib/postgresql/data
  api:
    image: robert076/logger2-api:v1
    container_name: api_logger2
    ports:
      - "8080:8080"
    env_file:
      - ./.env

volumes:
  logger2_data: