apiVersion: apps/v1
kind: Deployment
metadata:
  name: roberts-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: roberts-first-container
          image: robert076/logger2-api:9e0ec5d
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: logger2-storage
              mountPath: /path/in/container
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_DB
      volumes:
        - name: logger2-storage
          persistentVolumeClaim:
            claimName: db-pvc
